# Generated by Django 3.2.7 on 2021-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFCFilejson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedIfcFileUUID', models.SlugField()),
                ('projectUUID', models.SlugField()),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(max_length=200, verbose_name='file name')),
                ('userU', models.CharField(max_length=200, verbose_name='user who uploaded')),
                ('IFCjson', models.JSONField()),
                ('IFCFile', models.FileField(upload_to='ifcfiles/')),
            ],
        ),
    ]
