# Generated by Django 3.2.7 on 2021-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcfilejson',
            name='dateAndTime',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='ifcfilejson',
            name='IFCjson',
            field=models.FileField(upload_to='jsonFiles/'),
        ),
    ]
