# Generated by Django 3.2.7 on 2021-09-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210912_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcfilejson',
            name='IFCFile',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ifcfilejson',
            name='IFCjson',
            field=models.CharField(max_length=1000),
        ),
    ]
