# Generated by Django 3.2.7 on 2021-09-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210912_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifcfilejson',
            name='IFCFile',
        ),
        migrations.AlterField(
            model_name='ifcfilejson',
            name='IFCjson',
            field=models.JSONField(verbose_name='ifc json file'),
        ),
    ]
