# Generated by Django 3.2.7 on 2021-10-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210913_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcfilejson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
