# Generated by Django 3.2.7 on 2021-11-24 20:31

from django.db import migrations, models
import django.db.models.deletion
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_ifcfilejson_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcConvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectUUID', models.SlugField()),
                ('uploadedIfcFileUUID', models.SlugField()),
                ('name', models.CharField(max_length=200, verbose_name='file name')),
                ('userU', models.CharField(max_length=200, verbose_name='user who uploaded')),
                ('IFCFile', models.FileField(upload_to='files/IFCFile_model', validators=[portal.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='IfcResultModel',
            fields=[
                ('IfcFileID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.ifcconvertmodel')),
                ('IFCjsonResult', models.FileField(upload_to='files/IFCFile_json', verbose_name='json files')),
            ],
        ),
    ]
