# Generated by Django 3.2.7 on 2021-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_ifcconvertmodel_ifcresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcresultmodel',
            name='IFCjsonResult',
            field=models.JSONField(verbose_name='json files'),
        ),
    ]
